import * as RegionDef from './RegionDef.ts';

export const AllRegionList = [
    {
        label: RegionDef.REGION_SEOUL_STR,
        value: RegionDef.REGION_SEOUL,
    },
    {
        label: RegionDef.REGION_GYEONGGI_STR,
        value: RegionDef.REGION_GYEONGGI,
    },
    {
        label: RegionDef.REGION_INCHEON_STR,
        value: RegionDef.REGION_INCHEON,
    },
    {
        label: RegionDef.REGION_CHUNGCHEONGBUK_STR,
        value: RegionDef.REGION_CHUNGCHEONGBUK,
    },
    {
        label: RegionDef.REGION_CHUNGCHEONGNAM_STR,
        value: RegionDef.REGION_CHUNGCHEONGNAM,
    },
    {
        label: RegionDef.REGION_GANGWON_STR,
        value: RegionDef.REGION_GANGWON,
    },
    {
        label: RegionDef.REGION_BUSAN_STR,
        value: RegionDef.REGION_BUSAN,
    },
    {
        label: RegionDef.REGION_DAEGU_STR,
        value: RegionDef.REGION_DAEGU,
    },
    {
        label: RegionDef.REGION_GWANGJU_STR,
        value: RegionDef.REGION_GWANGJU,
    },
    {
        label: RegionDef.REGION_DAEJEON_STR,
        value: RegionDef.REGION_DAEJEON,
    },
    {
        label: RegionDef.REGION_ULSAN_STR,
        value: RegionDef.REGION_ULSAN,
    },
    {
        label: RegionDef.REGION_SEJONG_STR,
        value: RegionDef.REGION_SEJONG,
    },
    {
        label: RegionDef.REGION_JEJU_STR,
        value: RegionDef.REGION_JEJU,
    },
    {
        label: RegionDef.REGION_GYEONGSANGBUK_STR,
        value: RegionDef.REGION_GYEONGSANGBUK,
    },
    {
        label: RegionDef.REGION_GYEONGSANGNAM_STR,
        value: RegionDef.REGION_GYEONGSANGNAM,
    },
    {
        label: RegionDef.REGION_JEONBUK_STR,
        value: RegionDef.REGION_JEONBUK,
    },
    {
        label: RegionDef.REGION_JEONNAM_STR,
        value: RegionDef.REGION_JEONNAM,
    },
];

export const AllDistrictList: Record<number, { label: string; value: number }[]> = {
  [RegionDef.REGION_SEOUL]: [
    { label: RegionDef.DISTRICT_SEOUL_JONGNO_STR, value: RegionDef.DISTRICT_SEOUL_JONGNO },
    { label: RegionDef.DISTRICT_SEOUL_JUNG_STR, value: RegionDef.DISTRICT_SEOUL_JUNG },
    { label: RegionDef.DISTRICT_SEOUL_YONGSAN_STR, value: RegionDef.DISTRICT_SEOUL_YONGSAN },
    { label: RegionDef.DISTRICT_SEOUL_SEONGDONG_STR, value: RegionDef.DISTRICT_SEOUL_SEONGDONG },
    { label: RegionDef.DISTRICT_SEOUL_GWANGJIN_STR, value: RegionDef.DISTRICT_SEOUL_GWANGJIN },
    { label: RegionDef.DISTRICT_SEOUL_DONGDAEMUN_STR, value: RegionDef.DISTRICT_SEOUL_DONGDAEMUN },
    { label: RegionDef.DISTRICT_SEOUL_JUNGNANG_STR, value: RegionDef.DISTRICT_SEOUL_JUNGNANG },
    { label: RegionDef.DISTRICT_SEOUL_SEONGBUK_STR, value: RegionDef.DISTRICT_SEOUL_SEONGBUK },
    { label: RegionDef.DISTRICT_SEOUL_GANGBUK_STR, value: RegionDef.DISTRICT_SEOUL_GANGBUK },
    { label: RegionDef.DISTRICT_SEOUL_DOBONG_STR, value: RegionDef.DISTRICT_SEOUL_DOBONG },
    { label: RegionDef.DISTRICT_SEOUL_NOWON_STR, value: RegionDef.DISTRICT_SEOUL_NOWON },
    { label: RegionDef.DISTRICT_SEOUL_EUNPYEONG_STR, value: RegionDef.DISTRICT_SEOUL_EUNPYEONG },
    { label: RegionDef.DISTRICT_SEOUL_SEODAEMUN_STR, value: RegionDef.DISTRICT_SEOUL_SEODAEMUN },
    { label: RegionDef.DISTRICT_SEOUL_MAPO_STR, value: RegionDef.DISTRICT_SEOUL_MAPO },
    { label: RegionDef.DISTRICT_SEOUL_YANGCHEON_STR, value: RegionDef.DISTRICT_SEOUL_YANGCHEON },
    { label: RegionDef.DISTRICT_SEOUL_GANGSEO_STR, value: RegionDef.DISTRICT_SEOUL_GANGSEO },
    { label: RegionDef.DISTRICT_SEOUL_GURO_STR, value: RegionDef.DISTRICT_SEOUL_GURO },
    { label: RegionDef.DISTRICT_SEOUL_GEUMCHEON_STR, value: RegionDef.DISTRICT_SEOUL_GEUMCHEON },
    { label: RegionDef.DISTRICT_SEOUL_YEONGDEUNGPO_STR, value: RegionDef.DISTRICT_SEOUL_YEONGDEUNGPO },
    { label: RegionDef.DISTRICT_SEOUL_DONGJAK_STR, value: RegionDef.DISTRICT_SEOUL_DONGJAK },
    { label: RegionDef.DISTRICT_SEOUL_GWANAK_STR, value: RegionDef.DISTRICT_SEOUL_GWANAK },
    { label: RegionDef.DISTRICT_SEOUL_SEOCHO_STR, value: RegionDef.DISTRICT_SEOUL_SEOCHO },
    { label: RegionDef.DISTRICT_SEOUL_GANGNAM_STR, value: RegionDef.DISTRICT_SEOUL_GANGNAM },
    { label: RegionDef.DISTRICT_SEOUL_SONGPA_STR, value: RegionDef.DISTRICT_SEOUL_SONGPA },
    { label: RegionDef.DISTRICT_SEOUL_GANGDONG_STR, value: RegionDef.DISTRICT_SEOUL_GANGDONG },
  ],
  [RegionDef.REGION_GYEONGGI]: [
    { label: RegionDef.DISTRICT_GYEONGGI_SUWON_STR, value: RegionDef.DISTRICT_GYEONGGI_SUWON },
    { label: RegionDef.DISTRICT_GYEONGGI_SEONGNAM_STR, value: RegionDef.DISTRICT_GYEONGGI_SEONGNAM },
    { label: RegionDef.DISTRICT_GYEONGGI_UIJEONGBU_STR, value: RegionDef.DISTRICT_GYEONGGI_UIJEONGBU },
    { label: RegionDef.DISTRICT_GYEONGGI_ANYANG_STR, value: RegionDef.DISTRICT_GYEONGGI_ANYANG },
    { label: RegionDef.DISTRICT_GYEONGGI_BUCHEON_STR, value: RegionDef.DISTRICT_GYEONGGI_BUCHEON },
    { label: RegionDef.DISTRICT_GYEONGGI_GWANGMYEONG_STR, value: RegionDef.DISTRICT_GYEONGGI_GWANGMYEONG },
    { label: RegionDef.DISTRICT_GYEONGGI_PYEONGTAEK_STR, value: RegionDef.DISTRICT_GYEONGGI_PYEONGTAEK },
    { label: RegionDef.DISTRICT_GYEONGGI_DONGDUCHEON_STR, value: RegionDef.DISTRICT_GYEONGGI_DONGDUCHEON },
    { label: RegionDef.DISTRICT_GYEONGGI_ANSAN_STR, value: RegionDef.DISTRICT_GYEONGGI_ANSAN },
    { label: RegionDef.DISTRICT_GYEONGGI_GOYANG_STR, value: RegionDef.DISTRICT_GYEONGGI_GOYANG },
    { label: RegionDef.DISTRICT_GYEONGGI_GWACHEON_STR, value: RegionDef.DISTRICT_GYEONGGI_GWACHEON },
    { label: RegionDef.DISTRICT_GYEONGGI_GURI_STR, value: RegionDef.DISTRICT_GYEONGGI_GURI },
    { label: RegionDef.DISTRICT_GYEONGGI_NAMYANGJU_STR, value: RegionDef.DISTRICT_GYEONGGI_NAMYANGJU },
    { label: RegionDef.DISTRICT_GYEONGGI_OSAN_STR, value: RegionDef.DISTRICT_GYEONGGI_OSAN },
    { label: RegionDef.DISTRICT_GYEONGGI_SIHEUNG_STR, value: RegionDef.DISTRICT_GYEONGGI_SIHEUNG },
    { label: RegionDef.DISTRICT_GYEONGGI_GUNPO_STR, value: RegionDef.DISTRICT_GYEONGGI_GUNPO },
    { label: RegionDef.DISTRICT_GYEONGGI_UIWANG_STR, value: RegionDef.DISTRICT_GYEONGGI_UIWANG },
    { label: RegionDef.DISTRICT_GYEONGGI_HANAM_STR, value: RegionDef.DISTRICT_GYEONGGI_HANAM },
    { label: RegionDef.DISTRICT_GYEONGGI_YONGIN_STR, value: RegionDef.DISTRICT_GYEONGGI_YONGIN },
    { label: RegionDef.DISTRICT_GYEONGGI_PAJU_STR, value: RegionDef.DISTRICT_GYEONGGI_PAJU },
    { label: RegionDef.DISTRICT_GYEONGGI_ICHEON_STR, value: RegionDef.DISTRICT_GYEONGGI_ICHEON },
    { label: RegionDef.DISTRICT_GYEONGGI_ANSEONG_STR, value: RegionDef.DISTRICT_GYEONGGI_ANSEONG },
    { label: RegionDef.DISTRICT_GYEONGGI_GIMPO_STR, value: RegionDef.DISTRICT_GYEONGGI_GIMPO },
    { label: RegionDef.DISTRICT_GYEONGGI_HWASEONG_STR, value: RegionDef.DISTRICT_GYEONGGI_HWASEONG },
    { label: RegionDef.DISTRICT_GYEONGGI_GWANGJU_STR, value: RegionDef.DISTRICT_GYEONGGI_GWANGJU },
    { label: RegionDef.DISTRICT_GYEONGGI_YANGJU_STR, value: RegionDef.DISTRICT_GYEONGGI_YANGJU },
    { label: RegionDef.DISTRICT_GYEONGGI_POCHEON_STR, value: RegionDef.DISTRICT_GYEONGGI_POCHEON },
    { label: RegionDef.DISTRICT_GYEONGGI_YEOJU_STR, value: RegionDef.DISTRICT_GYEONGGI_YEOJU },
    { label: RegionDef.DISTRICT_GYEONGGI_YEONCHEON_STR, value: RegionDef.DISTRICT_GYEONGGI_YEONCHEON },
    { label: RegionDef.DISTRICT_GYEONGGI_GAPYEONG_STR, value: RegionDef.DISTRICT_GYEONGGI_GAPYEONG },
    { label: RegionDef.DISTRICT_GYEONGGI_YANGPYEONG_STR, value: RegionDef.DISTRICT_GYEONGGI_YANGPYEONG },
  ],
  [RegionDef.REGION_INCHEON]: [
    { label: RegionDef.DISTRICT_INCHEON_JUNG_STR, value: RegionDef.DISTRICT_INCHEON_JUNG },
    { label: RegionDef.DISTRICT_INCHEON_DONG_STR, value: RegionDef.DISTRICT_INCHEON_DONG },
    { label: RegionDef.DISTRICT_INCHEON_MICHUHOL_STR, value: RegionDef.DISTRICT_INCHEON_MICHUHOL },
    { label: RegionDef.DISTRICT_INCHEON_YEONSU_STR, value: RegionDef.DISTRICT_INCHEON_YEONSU },
    { label: RegionDef.DISTRICT_INCHEON_NAMDONG_STR, value: RegionDef.DISTRICT_INCHEON_NAMDONG },
    { label: RegionDef.DISTRICT_INCHEON_BUPYEONG_STR, value: RegionDef.DISTRICT_INCHEON_BUPYEONG },
    { label: RegionDef.DISTRICT_INCHEON_GYEYANG_STR, value: RegionDef.DISTRICT_INCHEON_GYEYANG },
    { label: RegionDef.DISTRICT_INCHEON_SEO_STR, value: RegionDef.DISTRICT_INCHEON_SEO },
    { label: RegionDef.DISTRICT_INCHEON_GANGHWA_STR, value: RegionDef.DISTRICT_INCHEON_GANGHWA },
    { label: RegionDef.DISTRICT_INCHEON_ONGJIN_STR, value: RegionDef.DISTRICT_INCHEON_ONGJIN },
  ],
  [RegionDef.REGION_CHUNGCHEONGBUK]: [
    { label: RegionDef.DISTRICT_CHUNGBUK_CHEONGJU_STR, value: RegionDef.DISTRICT_CHUNGBUK_CHEONGJU },
    { label: RegionDef.DISTRICT_CHUNGBUK_CHUNGJU_STR, value: RegionDef.DISTRICT_CHUNGBUK_CHUNGJU },
    { label: RegionDef.DISTRICT_CHUNGBUK_JECHEON_STR, value: RegionDef.DISTRICT_CHUNGBUK_JECHEON },
    { label: RegionDef.DISTRICT_CHUNGBUK_BOEUN_STR, value: RegionDef.DISTRICT_CHUNGBUK_BOEUN },
    { label: RegionDef.DISTRICT_CHUNGBUK_OKCHEON_STR, value: RegionDef.DISTRICT_CHUNGBUK_OKCHEON },
    { label: RegionDef.DISTRICT_CHUNGBUK_YEONGDONG_STR, value: RegionDef.DISTRICT_CHUNGBUK_YEONGDONG },
    { label: RegionDef.DISTRICT_CHUNGBUK_JEUNGPYEONG_STR, value: RegionDef.DISTRICT_CHUNGBUK_JEUNGPYEONG },
    { label: RegionDef.DISTRICT_CHUNGBUK_JINCHEON_STR, value: RegionDef.DISTRICT_CHUNGBUK_JINCHEON },
    { label: RegionDef.DISTRICT_CHUNGBUK_GOESAN_STR, value: RegionDef.DISTRICT_CHUNGBUK_GOESAN },
    { label: RegionDef.DISTRICT_CHUNGBUK_EUMSEONG_STR, value: RegionDef.DISTRICT_CHUNGBUK_EUMSEONG },
    { label: RegionDef.DISTRICT_CHUNGBUK_DANYANG_STR, value: RegionDef.DISTRICT_CHUNGBUK_DANYANG },
  ],
  [RegionDef.REGION_CHUNGCHEONGNAM]: [
    { label: RegionDef.DISTRICT_CHUNGNAM_CHEONAN_STR, value: RegionDef.DISTRICT_CHUNGNAM_CHEONAN },
    { label: RegionDef.DISTRICT_CHUNGNAM_GONGJU_STR, value: RegionDef.DISTRICT_CHUNGNAM_GONGJU },
    { label: RegionDef.DISTRICT_CHUNGNAM_BORYEONG_STR, value: RegionDef.DISTRICT_CHUNGNAM_BORYEONG },
    { label: RegionDef.DISTRICT_CHUNGNAM_ASAN_STR, value: RegionDef.DISTRICT_CHUNGNAM_ASAN },
    { label: RegionDef.DISTRICT_CHUNGNAM_SEOSAN_STR, value: RegionDef.DISTRICT_CHUNGNAM_SEOSAN },
    { label: RegionDef.DISTRICT_CHUNGNAM_NONSAN_STR, value: RegionDef.DISTRICT_CHUNGNAM_NONSAN },
    { label: RegionDef.DISTRICT_CHUNGNAM_GYERYONG_STR, value: RegionDef.DISTRICT_CHUNGNAM_GYERYONG },
    { label: RegionDef.DISTRICT_CHUNGNAM_DANGJIN_STR, value: RegionDef.DISTRICT_CHUNGNAM_DANGJIN },
    { label: RegionDef.DISTRICT_CHUNGNAM_GEUMSAN_STR, value: RegionDef.DISTRICT_CHUNGNAM_GEUMSAN },
    { label: RegionDef.DISTRICT_CHUNGNAM_BUYEO_STR, value: RegionDef.DISTRICT_CHUNGNAM_BUYEO },
    { label: RegionDef.DISTRICT_CHUNGNAM_SEOCHEON_STR, value: RegionDef.DISTRICT_CHUNGNAM_SEOCHEON },
    { label: RegionDef.DISTRICT_CHUNGNAM_CHEONGYANG_STR, value: RegionDef.DISTRICT_CHUNGNAM_CHEONGYANG },
    { label: RegionDef.DISTRICT_CHUNGNAM_HONGSEONG_STR, value: RegionDef.DISTRICT_CHUNGNAM_HONGSEONG },
    { label: RegionDef.DISTRICT_CHUNGNAM_YESAN_STR, value: RegionDef.DISTRICT_CHUNGNAM_YESAN },
    { label: RegionDef.DISTRICT_CHUNGNAM_TAEAN_STR, value: RegionDef.DISTRICT_CHUNGNAM_TAEAN },
  ],
  [RegionDef.REGION_GANGWON]: [
    { label: RegionDef.DISTRICT_GANGWON_CHUNCHEON_STR, value: RegionDef.DISTRICT_GANGWON_CHUNCHEON },
    { label: RegionDef.DISTRICT_GANGWON_WONJU_STR, value: RegionDef.DISTRICT_GANGWON_WONJU },
    { label: RegionDef.DISTRICT_GANGWON_GANGNEUNG_STR, value: RegionDef.DISTRICT_GANGWON_GANGNEUNG },
    { label: RegionDef.DISTRICT_GANGWON_DONGHAE_STR, value: RegionDef.DISTRICT_GANGWON_DONGHAE },
    { label: RegionDef.DISTRICT_GANGWON_TAEBAEK_STR, value: RegionDef.DISTRICT_GANGWON_TAEBAEK },
    { label: RegionDef.DISTRICT_GANGWON_SOKCHO_STR, value: RegionDef.DISTRICT_GANGWON_SOKCHO },
    { label: RegionDef.DISTRICT_GANGWON_SAMCHEOK_STR, value: RegionDef.DISTRICT_GANGWON_SAMCHEOK },
    { label: RegionDef.DISTRICT_GANGWON_HONGCHEON_STR, value: RegionDef.DISTRICT_GANGWON_HONGCHEON },
    { label: RegionDef.DISTRICT_GANGWON_HOENGSEONG_STR, value: RegionDef.DISTRICT_GANGWON_HOENGSEONG },
    { label: RegionDef.DISTRICT_GANGWON_YEONGWOL_STR, value: RegionDef.DISTRICT_GANGWON_YEONGWOL },
    { label: RegionDef.DISTRICT_GANGWON_PYEONGCHANG_STR, value: RegionDef.DISTRICT_GANGWON_PYEONGCHANG },
    { label: RegionDef.DISTRICT_GANGWON_JEONGSEON_STR, value: RegionDef.DISTRICT_GANGWON_JEONGSEON },
    { label: RegionDef.DISTRICT_GANGWON_CHEORWON_STR, value: RegionDef.DISTRICT_GANGWON_CHEORWON },
    { label: RegionDef.DISTRICT_GANGWON_HWACHEON_STR, value: RegionDef.DISTRICT_GANGWON_HWACHEON },
    { label: RegionDef.DISTRICT_GANGWON_YANGGU_STR, value: RegionDef.DISTRICT_GANGWON_YANGGU },
    { label: RegionDef.DISTRICT_GANGWON_INJE_STR, value: RegionDef.DISTRICT_GANGWON_INJE },
    { label: RegionDef.DISTRICT_GANGWON_GOSEONG_STR, value: RegionDef.DISTRICT_GANGWON_GOSEONG },
    { label: RegionDef.DISTRICT_GANGWON_YANGYANG_STR, value: RegionDef.DISTRICT_GANGWON_YANGYANG },
  ],
  [RegionDef.REGION_BUSAN]: [
    { label: RegionDef.DISTRICT_BUSAN_JUNG_STR, value: RegionDef.DISTRICT_BUSAN_JUNG },
    { label: RegionDef.DISTRICT_BUSAN_SEO_STR, value: RegionDef.DISTRICT_BUSAN_SEO },
    { label: RegionDef.DISTRICT_BUSAN_DONG_STR, value: RegionDef.DISTRICT_BUSAN_DONG },
    { label: RegionDef.DISTRICT_BUSAN_YEONGDO_STR, value: RegionDef.DISTRICT_BUSAN_YEONGDO },
    { label: RegionDef.DISTRICT_BUSAN_BUSANJIN_STR, value: RegionDef.DISTRICT_BUSAN_BUSANJIN },
    { label: RegionDef.DISTRICT_BUSAN_DONGNAE_STR, value: RegionDef.DISTRICT_BUSAN_DONGNAE },
    { label: RegionDef.DISTRICT_BUSAN_NAM_STR, value: RegionDef.DISTRICT_BUSAN_NAM },
    { label: RegionDef.DISTRICT_BUSAN_BUK_STR, value: RegionDef.DISTRICT_BUSAN_BUK },
    { label: RegionDef.DISTRICT_BUSAN_HAEUNDAE_STR, value: RegionDef.DISTRICT_BUSAN_HAEUNDAE },
    { label: RegionDef.DISTRICT_BUSAN_SAHA_STR, value: RegionDef.DISTRICT_BUSAN_SAHA },
    { label: RegionDef.DISTRICT_BUSAN_GEUMJEONG_STR, value: RegionDef.DISTRICT_BUSAN_GEUMJEONG },
    { label: RegionDef.DISTRICT_BUSAN_GANGSEO_STR, value: RegionDef.DISTRICT_BUSAN_GANGSEO },
    { label: RegionDef.DISTRICT_BUSAN_YEONJE_STR, value: RegionDef.DISTRICT_BUSAN_YEONJE },
    { label: RegionDef.DISTRICT_BUSAN_SUYEONG_STR, value: RegionDef.DISTRICT_BUSAN_SUYEONG },
    { label: RegionDef.DISTRICT_BUSAN_SASANG_STR, value: RegionDef.DISTRICT_BUSAN_SASANG },
    { label: RegionDef.DISTRICT_BUSAN_GIJANG_STR, value: RegionDef.DISTRICT_BUSAN_GIJANG },
  ],
  [RegionDef.REGION_DAEGU]: [
    { label: RegionDef.DISTRICT_DAEGU_JUNG_STR, value: RegionDef.DISTRICT_DAEGU_JUNG },
    { label: RegionDef.DISTRICT_DAEGU_DONG_STR, value: RegionDef.DISTRICT_DAEGU_DONG },
    { label: RegionDef.DISTRICT_DAEGU_SEO_STR, value: RegionDef.DISTRICT_DAEGU_SEO },
    { label: RegionDef.DISTRICT_DAEGU_NAM_STR, value: RegionDef.DISTRICT_DAEGU_NAM },
    { label: RegionDef.DISTRICT_DAEGU_BUK_STR, value: RegionDef.DISTRICT_DAEGU_BUK },
    { label: RegionDef.DISTRICT_DAEGU_SUSEONG_STR, value: RegionDef.DISTRICT_DAEGU_SUSEONG },
    { label: RegionDef.DISTRICT_DAEGU_DALSEO_STR, value: RegionDef.DISTRICT_DAEGU_DALSEO },
    { label: RegionDef.DISTRICT_DAEGU_DALSEONG_STR, value: RegionDef.DISTRICT_DAEGU_DALSEONG },
    { label: RegionDef.DISTRICT_DAEGU_GUNWI_STR, value: RegionDef.DISTRICT_DAEGU_GUNWI },
  ],
  [RegionDef.REGION_GWANGJU]: [
    { label: RegionDef.DISTRICT_GWANGJU_DONG_STR, value: RegionDef.DISTRICT_GWANGJU_DONG },
    { label: RegionDef.DISTRICT_GWANGJU_SEO_STR, value: RegionDef.DISTRICT_GWANGJU_SEO },
    { label: RegionDef.DISTRICT_GWANGJU_NAM_STR, value: RegionDef.DISTRICT_GWANGJU_NAM },
    { label: RegionDef.DISTRICT_GWANGJU_BUK_STR, value: RegionDef.DISTRICT_GWANGJU_BUK },
    { label: RegionDef.DISTRICT_GWANGJU_GWANGSAN_STR, value: RegionDef.DISTRICT_GWANGJU_GWANGSAN },
  ],
  [RegionDef.REGION_DAEJEON]: [
    { label: RegionDef.DISTRICT_DAEJEON_DONG_STR, value: RegionDef.DISTRICT_DAEJEON_DONG },
    { label: RegionDef.DISTRICT_DAEJEON_JUNG_STR, value: RegionDef.DISTRICT_DAEJEON_JUNG },
    { label: RegionDef.DISTRICT_DAEJEON_SEO_STR, value: RegionDef.DISTRICT_DAEJEON_SEO },
    { label: RegionDef.DISTRICT_DAEJEON_YUSEONG_STR, value: RegionDef.DISTRICT_DAEJEON_YUSEONG },
    { label: RegionDef.DISTRICT_DAEJEON_DAEDEOK_STR, value: RegionDef.DISTRICT_DAEJEON_DAEDEOK },
  ],
  [RegionDef.REGION_ULSAN]: [
    { label: RegionDef.DISTRICT_ULSAN_JUNG_STR, value: RegionDef.DISTRICT_ULSAN_JUNG },
    { label: RegionDef.DISTRICT_ULSAN_NAM_STR, value: RegionDef.DISTRICT_ULSAN_NAM },
    { label: RegionDef.DISTRICT_ULSAN_DONG_STR, value: RegionDef.DISTRICT_ULSAN_DONG },
    { label: RegionDef.DISTRICT_ULSAN_BUK_STR, value: RegionDef.DISTRICT_ULSAN_BUK },
    { label: RegionDef.DISTRICT_ULSAN_ULJU_STR, value: RegionDef.DISTRICT_ULSAN_ULJU },
  ],
  [RegionDef.REGION_SEJONG]: [
    { label: RegionDef.DISTRICT_SEJONG_STR, value: RegionDef.DISTRICT_SEJONG },
  ],
  [RegionDef.REGION_JEJU]: [
    { label: RegionDef.DISTRICT_JEJU_JEJU_STR, value: RegionDef.DISTRICT_JEJU_JEJU },
    { label: RegionDef.DISTRICT_JEJU_SEOGWIPO_STR, value: RegionDef.DISTRICT_JEJU_SEOGWIPO },
  ],
  [RegionDef.REGION_GYEONGSANGBUK]: [
    { label: RegionDef.DISTRICT_GYEONGBUK_POHANG_STR, value: RegionDef.DISTRICT_GYEONGBUK_POHANG },
    { label: RegionDef.DISTRICT_GYEONGBUK_GYEONGJU_STR, value: RegionDef.DISTRICT_GYEONGBUK_GYEONGJU },
    { label: RegionDef.DISTRICT_GYEONGBUK_GIMCHEON_STR, value: RegionDef.DISTRICT_GYEONGBUK_GIMCHEON },
    { label: RegionDef.DISTRICT_GYEONGBUK_ANDONG_STR, value: RegionDef.DISTRICT_GYEONGBUK_ANDONG },
    { label: RegionDef.DISTRICT_GYEONGBUK_GUMI_STR, value: RegionDef.DISTRICT_GYEONGBUK_GUMI },
    { label: RegionDef.DISTRICT_GYEONGBUK_YEONGJU_STR, value: RegionDef.DISTRICT_GYEONGBUK_YEONGJU },
    { label: RegionDef.DISTRICT_GYEONGBUK_YEONGCHEON_STR, value: RegionDef.DISTRICT_GYEONGBUK_YEONGCHEON },
    { label: RegionDef.DISTRICT_GYEONGBUK_SANGJU_STR, value: RegionDef.DISTRICT_GYEONGBUK_SANGJU },
    { label: RegionDef.DISTRICT_GYEONGBUK_MUNGYEONG_STR, value: RegionDef.DISTRICT_GYEONGBUK_MUNGYEONG },
    { label: RegionDef.DISTRICT_GYEONGBUK_GYEONGSAN_STR, value: RegionDef.DISTRICT_GYEONGBUK_GYEONGSAN },
    { label: RegionDef.DISTRICT_GYEONGBUK_UISEONG_STR, value: RegionDef.DISTRICT_GYEONGBUK_UISEONG },
    { label: RegionDef.DISTRICT_GYEONGBUK_CHEONGSONG_STR, value: RegionDef.DISTRICT_GYEONGBUK_CHEONGSONG },
    { label: RegionDef.DISTRICT_GYEONGBUK_YEONGYANG_STR, value: RegionDef.DISTRICT_GYEONGBUK_YEONGYANG },
    { label: RegionDef.DISTRICT_GYEONGBUK_YEONGDEOK_STR, value: RegionDef.DISTRICT_GYEONGBUK_YEONGDEOK },
    { label: RegionDef.DISTRICT_GYEONGBUK_CHEONGDO_STR, value: RegionDef.DISTRICT_GYEONGBUK_CHEONGDO },
    { label: RegionDef.DISTRICT_GYEONGBUK_GORYEONG_STR, value: RegionDef.DISTRICT_GYEONGBUK_GORYEONG },
    { label: RegionDef.DISTRICT_GYEONGBUK_SEONGJU_STR, value: RegionDef.DISTRICT_GYEONGBUK_SEONGJU },
    { label: RegionDef.DISTRICT_GYEONGBUK_CHILGOK_STR, value: RegionDef.DISTRICT_GYEONGBUK_CHILGOK },
    { label: RegionDef.DISTRICT_GYEONGBUK_YECHEON_STR, value: RegionDef.DISTRICT_GYEONGBUK_YECHEON },
    { label: RegionDef.DISTRICT_GYEONGBUK_BONGHWA_STR, value: RegionDef.DISTRICT_GYEONGBUK_BONGHWA },
    { label: RegionDef.DISTRICT_GYEONGBUK_ULJIN_STR, value: RegionDef.DISTRICT_GYEONGBUK_ULJIN },
    { label: RegionDef.DISTRICT_GYEONGBUK_ULLEUNG_STR, value: RegionDef.DISTRICT_GYEONGBUK_ULLEUNG },
  ],
  [RegionDef.REGION_GYEONGSANGNAM]: [
    { label: RegionDef.DISTRICT_GYEONGNAM_CHANGWON_STR, value: RegionDef.DISTRICT_GYEONGNAM_CHANGWON },
    { label: RegionDef.DISTRICT_GYEONGNAM_JINJU_STR, value: RegionDef.DISTRICT_GYEONGNAM_JINJU },
    { label: RegionDef.DISTRICT_GYEONGNAM_TONGYEONG_STR, value: RegionDef.DISTRICT_GYEONGNAM_TONGYEONG },
    { label: RegionDef.DISTRICT_GYEONGNAM_SACHEON_STR, value: RegionDef.DISTRICT_GYEONGNAM_SACHEON },
    { label: RegionDef.DISTRICT_GYEONGNAM_GIMHAE_STR, value: RegionDef.DISTRICT_GYEONGNAM_GIMHAE },
    { label: RegionDef.DISTRICT_GYEONGNAM_MIRYANG_STR, value: RegionDef.DISTRICT_GYEONGNAM_MIRYANG },
    { label: RegionDef.DISTRICT_GYEONGNAM_GEOJE_STR, value: RegionDef.DISTRICT_GYEONGNAM_GEOJE },
    { label: RegionDef.DISTRICT_GYEONGNAM_YANGSAN_STR, value: RegionDef.DISTRICT_GYEONGNAM_YANGSAN },
    { label: RegionDef.DISTRICT_GYEONGNAM_UIRYEONG_STR, value: RegionDef.DISTRICT_GYEONGNAM_UIRYEONG },
    { label: RegionDef.DISTRICT_GYEONGNAM_HAMAN_STR, value: RegionDef.DISTRICT_GYEONGNAM_HAMAN },
    { label: RegionDef.DISTRICT_GYEONGNAM_CHANGNYEONG_STR, value: RegionDef.DISTRICT_GYEONGNAM_CHANGNYEONG },
    { label: RegionDef.DISTRICT_GYEONGNAM_GOSEONG_STR, value: RegionDef.DISTRICT_GYEONGNAM_GOSEONG },
    { label: RegionDef.DISTRICT_GYEONGNAM_NAMHAE_STR, value: RegionDef.DISTRICT_GYEONGNAM_NAMHAE },
    { label: RegionDef.DISTRICT_GYEONGNAM_HADONG_STR, value: RegionDef.DISTRICT_GYEONGNAM_HADONG },
    { label: RegionDef.DISTRICT_GYEONGNAM_SANCHEONG_STR, value: RegionDef.DISTRICT_GYEONGNAM_SANCHEONG },
    { label: RegionDef.DISTRICT_GYEONGNAM_HAMYANG_STR, value: RegionDef.DISTRICT_GYEONGNAM_HAMYANG },
    { label: RegionDef.DISTRICT_GYEONGNAM_GEOCHANG_STR, value: RegionDef.DISTRICT_GYEONGNAM_GEOCHANG },
    { label: RegionDef.DISTRICT_GYEONGNAM_HAPCHEON_STR, value: RegionDef.DISTRICT_GYEONGNAM_HAPCHEON },
  ],
  [RegionDef.REGION_JEONBUK]: [
    { label: RegionDef.DISTRICT_JEONBUK_JEONJU_STR, value: RegionDef.DISTRICT_JEONBUK_JEONJU },
    { label: RegionDef.DISTRICT_JEONBUK_GUNSAN_STR, value: RegionDef.DISTRICT_JEONBUK_GUNSAN },
    { label: RegionDef.DISTRICT_JEONBUK_IKSAN_STR, value: RegionDef.DISTRICT_JEONBUK_IKSAN },
    { label: RegionDef.DISTRICT_JEONBUK_JEONGEUP_STR, value: RegionDef.DISTRICT_JEONBUK_JEONGEUP },
    { label: RegionDef.DISTRICT_JEONBUK_NAMWON_STR, value: RegionDef.DISTRICT_JEONBUK_NAMWON },
    { label: RegionDef.DISTRICT_JEONBUK_GIMJE_STR, value: RegionDef.DISTRICT_JEONBUK_GIMJE },
    { label: RegionDef.DISTRICT_JEONBUK_WANJU_STR, value: RegionDef.DISTRICT_JEONBUK_WANJU },
    { label: RegionDef.DISTRICT_JEONBUK_JINAN_STR, value: RegionDef.DISTRICT_JEONBUK_JINAN },
    { label: RegionDef.DISTRICT_JEONBUK_MUJU_STR, value: RegionDef.DISTRICT_JEONBUK_MUJU },
    { label: RegionDef.DISTRICT_JEONBUK_JANGSU_STR, value: RegionDef.DISTRICT_JEONBUK_JANGSU },
    { label: RegionDef.DISTRICT_JEONBUK_IMSIL_STR, value: RegionDef.DISTRICT_JEONBUK_IMSIL },
    { label: RegionDef.DISTRICT_JEONBUK_SUNCHANG_STR, value: RegionDef.DISTRICT_JEONBUK_SUNCHANG },
    { label: RegionDef.DISTRICT_JEONBUK_GOCHANG_STR, value: RegionDef.DISTRICT_JEONBUK_GOCHANG },
    { label: RegionDef.DISTRICT_JEONBUK_BUAN_STR, value: RegionDef.DISTRICT_JEONBUK_BUAN },
  ],
  [RegionDef.REGION_JEONNAM]: [
    { label: RegionDef.DISTRICT_JEONNAM_MOKPO_STR, value: RegionDef.DISTRICT_JEONNAM_MOKPO },
    { label: RegionDef.DISTRICT_JEONNAM_YEOSU_STR, value: RegionDef.DISTRICT_JEONNAM_YEOSU },
    { label: RegionDef.DISTRICT_JEONNAM_SUNCHEON_STR, value: RegionDef.DISTRICT_JEONNAM_SUNCHEON },
    { label: RegionDef.DISTRICT_JEONNAM_NAJU_STR, value: RegionDef.DISTRICT_JEONNAM_NAJU },
    { label: RegionDef.DISTRICT_JEONNAM_GWANGYANG_STR, value: RegionDef.DISTRICT_JEONNAM_GWANGYANG },
    { label: RegionDef.DISTRICT_JEONNAM_DAMYANG_STR, value: RegionDef.DISTRICT_JEONNAM_DAMYANG },
    { label: RegionDef.DISTRICT_JEONNAM_GOKSEONG_STR, value: RegionDef.DISTRICT_JEONNAM_GOKSEONG },
    { label: RegionDef.DISTRICT_JEONNAM_GURYE_STR, value: RegionDef.DISTRICT_JEONNAM_GURYE },
    { label: RegionDef.DISTRICT_JEONNAM_GOHEUNG_STR, value: RegionDef.DISTRICT_JEONNAM_GOHEUNG },
    { label: RegionDef.DISTRICT_JEONNAM_BOSEONG_STR, value: RegionDef.DISTRICT_JEONNAM_BOSEONG },
    { label: RegionDef.DISTRICT_JEONNAM_HWASUN_STR, value: RegionDef.DISTRICT_JEONNAM_HWASUN },
    { label: RegionDef.DISTRICT_JEONNAM_JANGHEUNG_STR, value: RegionDef.DISTRICT_JEONNAM_JANGHEUNG },
    { label: RegionDef.DISTRICT_JEONNAM_GANGJIN_STR, value: RegionDef.DISTRICT_JEONNAM_GANGJIN },
    { label: RegionDef.DISTRICT_JEONNAM_HAENAM_STR, value: RegionDef.DISTRICT_JEONNAM_HAENAM },
    { label: RegionDef.DISTRICT_JEONNAM_YEONGAM_STR, value: RegionDef.DISTRICT_JEONNAM_YEONGAM },
    { label: RegionDef.DISTRICT_JEONNAM_MUAN_STR, value: RegionDef.DISTRICT_JEONNAM_MUAN },
    { label: RegionDef.DISTRICT_JEONNAM_HAMPYEONG_STR, value: RegionDef.DISTRICT_JEONNAM_HAMPYEONG },
    { label: RegionDef.DISTRICT_JEONNAM_YEONGGWANG_STR, value: RegionDef.DISTRICT_JEONNAM_YEONGGWANG },
    { label: RegionDef.DISTRICT_JEONNAM_JANGSEONG_STR, value: RegionDef.DISTRICT_JEONNAM_JANGSEONG },
    { label: RegionDef.DISTRICT_JEONNAM_WANDO_STR, value: RegionDef.DISTRICT_JEONNAM_WANDO },
    { label: RegionDef.DISTRICT_JEONNAM_JINDO_STR, value: RegionDef.DISTRICT_JEONNAM_JINDO },
    { label: RegionDef.DISTRICT_JEONNAM_SINAN_STR, value: RegionDef.DISTRICT_JEONNAM_SINAN },
  ],
};